### PR TITLE
Export citePlugin as default

### LINKED ISSUE #1: Citations converted to text node not citeItems
I'm trying to use Remark (via `remark-cli`) to ensure uniform formatting in my Markdown documents; as I use Pandoc I'd like to use `remark-cite` to preserve the citations (as otherwise, the opening square bracket is escaped with a backslash). However, including the plugin doesn't appear to affect the output that is generated.

Using the example from the documentation:

`test.md`:
```markdown
[see @wadler1989, sec. 1.3; and -@hughes1990, pp.4]
```

Minimal config in `~/.remarkrc.yml` (other plugins/settings removed to confirm they're not interfering):
```yaml
plugins:
  - "@benrbray/remark-cite"
```

```
$ remark --tree-out ~/test.md
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "text",
          "value": "[see @wadler1989, sec. 1.3; and -@hughes1990, pp.4]",
          "position": {
            "start": {
              "line": 1,
              "column": 1,
              "offset": 0
            },
            "end": {
              "line": 1,
              "column": 52,
              "offset": 51
            }
          }
        }
      ],
      "position": {
        "start": {
          "line": 1,
          "column": 1,
          "offset": 0
        },
        "end": {
          "line": 1,
          "column": 52,
          "offset": 51
        }
      }
    }
  ],
  "position": {
    "start": {
      "line": 1,
      "column": 1,
      "offset": 0
    },
    "end": {
      "line": 2,
      "column": 1,
      "offset": 52
    }
  }
}
```

I feel like this might be a misconfiguration on my part, as I found the documentation for config files and how plugin settings map onto them to be a little unclear, and I had issues with that with other settings. But in this case `enablePandocSyntax` should be true by default, and it doesn't even seem to be parsing in the first place — but I presume the module _is_ being loaded, because specifying a nonexistent plugin name causes an error. Any suggestions for how to debug this would be appreciated.

### PR DESCRIPTION
**Pull request by benjamineskola**
This seems to fix #1 by exporting a default method.

I've also ensured `options` is set, because otherwise I got an exception:

```
  1:1  error  TypeError: Cannot read property 'syntax' of undefined
    at Function.citePlugin (/Users/ben/Code/remark-cite/remark-cite/dist/index.cjs.js:21:72)
…
```

I'm not sure if there's a better way of writing that — I've never used typescript before.

### CODE REVIEW

**Comment by benrbray** [comment]
Thanks for the PR!  I tried testing this locally with `remark-cli` (by installing `remark-cli` alongside `remark-cite` in a project, but replacing the `@benrbray/remark-cite` version string in `package.json` with the path to my local copy of your fork).  

Were you able to successfully test this locally?  What was your setup?

**Comment by benrbray** [comment]
Also as a side note:  I think this will be a breaking change to the package since it changes how the `citePlugin` needs to be imported (as a default rather than named export).  So I will need to bump the major version.  I don't mind doing this as long as it does indeed fix the issue with `remark-cli`.

**Comment by benjamineskola** [comment]
I ran this locally by doing `npm run build` then `npm install -g`, and I was able to confirm that my `…/node_modules/@benrbray/remark-cite/dist/index.*.js` had the changes applied.

Then I was able to run `remark test.md` as normal and see first of all that in debug mode the extension was listed as being loaded (when it hadn't previously), and secondly that the output was as expected (citation nodes in the AST output, preserved citations in the markdown output).

**Comment by benrbray** [comment]
`remark-cite` now has a default export, so I believe this issue is resolved.  Let me know if that's not the case!

**Pull request closed without merging**
